### PR TITLE
`<Modal>`: Fix- disable page scrolling when modal is open

### LINKED ISSUE #2846: Background is scrolling with open Modal
# Bug Report

### Relevant Components
Modal

### Current Behavior
When Modal is open we still can scroll the background. No matter which parameters we pass to scrollable or scrollableContent props.

### Expected Behavior
Only Modal content should be scrollable.

### Steps to Reproduce
Just add a Modal component to any page that can be scrolled.

### Steps to Fix
Add overflow: 'hidden' to body element when Modal opens and set it back to 'visible' when Modal is closed

### Severity
Major

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary
Resolves #2846
disable page scrolling when modal is open.
reactjs/react-modal#191
...

### ✅ Checklist
- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [x] Story
  - [ ] API description
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

### CODE REVIEW

**Comment by TalZa1810** [comment]
Hey @hepiyellow ,
I created a new PR instead of the old one:
https://github.com/wix/wix-style-react/pull/3059

File: src/Modal/docs/ModalTestsStory.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
+import React from 'react';
+import { storiesOf } from '@storybook/react';
```
Comment (argshook) [inline src/Modal/docs/ModalTestsStory.js]: @TalZa1810 please put test story under `src/Modal/test/TestStory.js`

File: src/Modal/Modal.uni.driver.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import { baseUniDriverFactory } from 'wix-ui-test-utils/base-driver';
+import styles from './Modal.scss';
+
+export const modalDriverFactory = (base, body) => {
+  const modalContainerDriver = body.$(`.${styles.childrenContainer}`);
+
+  return {
+    ...baseUniDriverFactory(base),
+    isModalDisplayed: () => modalContainerDriver.isDisplayed(),
```
Comment (argshook) [inline src/Modal/Modal.uni.driver.js]: @TalZa1810 there already is a `.driver.js` which is what we export for users. This means `isModalDisplayed` will not reach users until `.driver.js` is fully migrated to `.uni.driver.js`

as this is out of scope for this PR i think it's ok not to do it now, but if `.uni.driver.js` is introduced, eventually it should be fully migrated. please ping Shlomi about it, maybe it can be the next task

File: testkit/protractor.js [hunk 3]
```diff
@@ -207,6 +207,12 @@ export const loaderTestkitFactory = protractorTestkitFactoryCreator(
   loaderDriverFactory,
 );
 
+import { modalDriverFactory } from '../src/Modal/Modal.uni.driver';
+
+export const modalTestkitFactory = protractorUniTestkitFactoryCreator(
```
Comment (argshook) [inline testkit/protractor.js]: @TalZa1810  same (almost) thing should happen also in `testkit/puppeteer.js`

File: src/Modal/Modal.uni.driver.js (hunk 2 above)
Comment (TalZa1810) [reply src/Modal/Modal.uni.driver.js]: Hi @shlomitc, 
WDYT?

File: src/Modal/Modal.js [hunk 4]
```diff
@@ -68,6 +68,7 @@ class Modal extends WixComponent {
       appElement,
       overlayPosition,
       parentSelector,
+      modalDataHook,
```
Comment (TalZa1810) [inline src/Modal/Modal.js]: remove

File: src/Modal/Modal.e2e.js [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+
+  const testStoryUrl = testName =>
+    createTestStoryUrl({ category, storyName, testName });
+  const createDriver = async (dataHook = storySettings.dataHook) => {
+    const driver = modalTestkitFactory({ dataHook });
+    await browser.wait(driver.exists(), 5000, 'Cannot find <Modal/>');
+    return driver;
+  };
+
+  const DATA_HOOKS = {
```
Comment (TalZa1810) [inline src/Modal/Modal.e2e.js]: remove

File: src/Modal/Modal.e2e.js [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+      await browser.get(testStoryUrl('1. Prevent modal background scroll'));
+    });
+
+    eyes.it('should add overflow to body once Modal is open', async () => {
+      const buttonDriver = buttonTestkitFactory({
+        dataHook: DATA_HOOKS.openModalButton,
+      });
+      await browser.wait(buttonDriver.exists(), 5000, 'Cannot find <Button/>');
+
+      await buttonDriver.click();
```
Comment (TalZa1810) [inline src/Modal/Modal.e2e.js]: simplify tests - just use the opened modal instead of opening it programmatically

File: src/Modal/Modal.private.uni.driver.js [hunk 7]
```diff
@@ -0,0 +1,8 @@
+import { modalDriverFactory as publicDriverFactory } from './Modal.uni.driver';
```
Comment (TalZa1810) [inline src/Modal/Modal.private.uni.driver.js]: remove

File: src/Modal/Modal.uni.driver.js [hunk 8]
```diff
@@ -0,0 +1,11 @@
+import { baseUniDriverFactory } from 'wix-ui-test-utils/base-driver';
```
Comment (TalZa1810) [inline src/Modal/Modal.uni.driver.js]: remove

File: src/Modal/Modal.e2e.js [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+    openModalButton: 'open-modal-button',
+  };
+
+  eyes.it('should render', async () => {
+    await createDriver();
+  });
+
+  describe('test stories', () => {
+    beforeAll(async () => {
+      await browser.get(testStoryUrl('1. Prevent modal background scroll'));
```
Comment (TalZa1810) [inline src/Modal/Modal.e2e.js]: create `src/Modal/test/storySettings` with an exported `testStories`, to reuse the test name

**Comment by aharoldk** [comment]
hello, it still happen when you open safari in ipad version 12.0.1
