### PR TITLE
<Tooltip> - Add instance methods to .d.ts

### LINKED ISSUE #3422: <Tooltip / > - Missing type definitions / declarations for instance methods.
# 🐛 Bug Report
Tooltip is Missing type definitions for it's instance methods, specifically "hide" in our case.
this yields a TS error
...

### 😯 Current Behavior
my component has:
`private tooltipRef: Tootlip`
and renders:
```ts

        <Tooltip
          ref={t => this.tooltipRef = t}
          ...
        >
          <span>{element}</span>
        </Tooltip>
```
and then using the ref to:
```this.tooltipRef.hide({ hideDelay: 0 });```

### 👀 Severity
- **Critical** - build brakes 🤷‍♂ 

workaround: not using a type 👎

### PR DESCRIPTION
**Pull request by NitayRabi**
Closes #3422
### 🔦 Summary
- Types should refer to instance methods and not only prop types (change broke users using ref)

- In order to support (and detect) the different API used in new (upgrade) and current Tooltip - used generic + conditional types.

- Currently only exposed `show`/`hide`/`close`/`open` methods
	- other methods which I chose currently not to expose (in old API, should 					 consider refactoring into private (_*) methods)
		- `getTriggers`
		- `renderTooltipIntoContainer`
		- `onClickOutside`
- New and Old API not matching (if someone passes upgrade flag and uses `hide`/`show` - it will break. if someone uses `open`/`close` without `upgrade` flag it will break) - should consider implementing empty methods with deprecation logs.

Tested in `.tsx` file.

### ✅ Checklist
- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [ ] Visual test

### CODE REVIEW

File: src/Tooltip/index.d.ts [hunk 1]
```diff
@@ -63,7 +63,16 @@ export interface TooltipOldProps extends WixComponentProps {
 
 export type TooltipProps = TooltipNewProps | TooltipOldProps;
 
-export default class Tooltip extends React.PureComponent<TooltipProps> {}
+export default class Tooltip<T extends TooltipProps> extends React.PureComponent<T> {
+  /** @deprecated use `upgrade` prop with `close` method */
+  hide: T extends { upgrade: true } ?  undefined: (props?: TooltipProps) => void ;
```
Comment (giladsegal) [inline src/Tooltip/index.d.ts]: probably should be type `never` and `upgrade: false` for `hide` and `show`
should be `never` for `close` and `open`
very good job! really cool idea :)

**Comment by shlomitc** [comment]
@giladartzi @NitayRabi - is everything here solved? can it be merged?

**Comment by NitayRabi** [comment]
> @giladartzi @NitayRabi - is everything here solved? can it be merged?

Fixed comments by @giladsegal - will merge after build.
