### PR TITLE
fix - do not call onSelect when selecting a selected option

### LINKED ISSUE #258: Dropdown doesn't close when clicking on a selected option

### PR DESCRIPTION
**Pull request by lbelinsk**
close #258

### CODE REVIEW

File: src/DropdownLayout/DropdownLayout.js [hunk 1]
```diff
@@ -48,8 +48,9 @@ class DropdownLayout extends WixComponent {
     const {options, onSelect, selectedId} = this.props;
     if (index >= 0 && index < options.length) {
       const newSelectedId = options[index].id;
-      if (newSelectedId !== selectedId && onSelect) {
-        onSelect(options[index]);
+      const isSelectedOptionSelected = newSelectedId === selectedId;
```
Comment (mastertheblaster) [inline src/DropdownLayout/DropdownLayout.js]: If's are good, but not guess to complicated, what if I would suggest you:

1) Exactly the same behavior but with less code:
```jsx
_onSelect(index) {
  const {options, onSelect, selectedId} = this.props;
  if (onSelect && options[index]) {
    onSelect(options[index], options[index].id === selectedId);
    return true;
  }
  return false;
}
```

2) Not sure you need to check `options` and `index`, cause otherwise the event wont be fired, so...
```jsx
_onSelect(index) {
  const {options, onSelect, selectedId} = this.props;
  onSelect && onSelect(options[index], options[index].id === selectedId);
  return !!onSelect;
}
```

File: src/InputWithOptions/InputWithOptions.js [hunk 2]
```diff
@@ -106,15 +106,17 @@ class InputWithOptions extends WixComponent {
...
+  _onSelect(option, isSelectedOption) {
     this.showOptions();
     const {onSelect} = this.props;
 
     if (this.closeOnSelect()) {
       this.hideOptions();
     }
 
-    if (onSelect) {
+    if (isSelectedOption) {
```
Comment (mastertheblaster) [inline src/InputWithOptions/InputWithOptions.js]: Not sure if this is good. Cause, `DropdownLayout` is firing `onSelect` even if the same option is selected and `InputWithOptions` not. Guess we should be consistent.

```jsx
isSelectedOption && this.setState({ showOptions: false });
onSelect && onSelect(option);
```

What do you say ?

File: src/DropdownLayout/DropdownLayout.js (hunk 1 above)
Comment (lbelinsk) [inline src/DropdownLayout/DropdownLayout.js]: I will try your second suggestion.. It is shorter but might be a bit less readable.. but it is nice..

File: src/InputWithOptions/InputWithOptions.js (hunk 2 above)
Comment (lbelinsk) [inline src/InputWithOptions/InputWithOptions.js]: There is a slight issue that I rather not call onSelect at all when we select the selected option.. In your suggestion we will call onSelect even if we have selected the selected option. It is a minor issue but I think it is better not to trigger the onSelect  on the selected value at all.. I even added a test that checks that the onSelect callback isn't triggered..

File: src/DropdownLayout/DropdownLayout.js (hunk 1 above)
Comment (lbelinsk) [inline src/DropdownLayout/DropdownLayout.js]: Actually I tried this now and some tests fail..
we must add to the last line:

```return !!onSelect && options[index];```

**Comment by lbelinsk** [comment]
@mastertheblaster thanks for the review!

I have committed a refactor after your review. please merge these changes if you approve. thanks 👍
