### PR TITLE
`<SegmentedToggle/>`- Adding options divider 

### LINKED ISSUE #3509: <SegmentedToggle/> - Divider between options is missing
# 🐛 Bug Report

### 🏗 Relevant Components
`<SegmentedToggle/>`

...

### 😯 Current Behavior

The component is missing a divider between options
Currently: 
image

In spec:

image

...

### 🤔 Expected Behavior

Should be a divider between options:

image

image

...

### 👣 Steps to Reproduce

  - **WSR version**: `...`
  - **Yoshi version**: `...`

### 👀 Severity
Low

### PR DESCRIPTION
**Pull request by TalZa1810**
### 🔦 Summary
Resolves #3509 

### ✅ Checklist
- [ ] 👨‍💻 API change is approved by the UI Infra Developers 
- [ ] 👨‍🎨 UX change is approved by the Design System UX 
- 📚 Change is documented
  - [ ] Story
  - [ ] API description
  - [ ] Other (explain)
- 🔬 Change is tested
  - [ ] Component
  - [x] Visual test

### CODE REVIEW

File: src/SegmentedToggle/SegmentedToggle.js [hunk 1]
```diff
@@ -29,6 +30,35 @@ class SegmentedToggle extends React.Component {
     this.setState({ selected: value }, () => onClick && onClick(evt, value));
   };
 
+  _addDividers = (childrenNodes, disabled) => {
+    const childrenNodesWithDividers = [];
+
+    const isTransparent = (childNode1, childNode2) =>
+      (childNode1.props.selected && !childNode2.props.selected) ||
```
Comment (mosheKerbel) [inline src/SegmentedToggle/SegmentedToggle.js]: can't this get the job done?
```childNode1.props.selected !== childNode2.props.selected```

File: src/SegmentedToggle/SegmentedToggle.js [hunk 2]
```diff
@@ -29,6 +30,35 @@ class SegmentedToggle extends React.Component {
...
+
+    for (let i = 0; i < childrenNodes.length - 1; i++) {
+      const childNode1 = childrenNodes[i];
+      const childNode2 = childrenNodes[i + 1];
+
+      const transparent = isTransparent(childNode1, childNode2);
+
+      const dividerClassNames = classNames(
+        styles.divider,
+        disabled && styles.disabled,
```
Comment (mosheKerbel) [inline src/SegmentedToggle/SegmentedToggle.js]: this is what i would do with css-modules but here we are using Stylable
so disabled and transparent should be passed as states
This way you will also be able to avoid this odd manipulation of the children cloned elements.

You can see for example how i manage the states in the new Stepper component
I can explain face to face if you like.

**Comment by mosheKerbel** [comment]
Visual tests are missing.

File: src/SegmentedToggle/SegmentedToggle.js [hunk 3]
```diff
@@ -48,7 +48,12 @@ class SegmentedToggle extends React.Component {
         />
       );
 
-      childrenNodesWithDividers.push(childNode1, divider, childNode2);
+      childrenNodesWithDividers.push(childNode1, divider);
+
+      //adding the last child to the array
```
Comment (mosheKerbel) [inline src/SegmentedToggle/SegmentedToggle.js]: i try to avoid using comments by making the code more readable, suggestion:
```
const isLastChild = childNode2 === children[children.length -1];
if (isLastChild) {
   childrenNodesWithDividers.push(childNode2);
}
